name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a master si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Aquí indicas la ruta exacta de tus archivos
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Website/proto-src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
